name: Auto Update M3U

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Run Script
        run: python generate.py

      - name: Save and Push M3U
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "Updated playlist" || exit 0
          git push
