name: Generate Playlist and Live Channel

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install yt-dlp requests

      - name: Run Stream Script
        run: |
          python stream.py

      - name: Auto Commit and Push Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlist and live stream"
          file_pattern: "playlist.m3u live_channel.m3u8"
